base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("", include("user.urls")),
]

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

pages/models.py
from io import BytesIO

from PIL import Image
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.utils.translation import gettext as _
from filetype import guess


# Create your models here.
def get_image_filepath(self, filename):
    file_extension = filename[filename.rfind(".") :]
    return f"posts/{self.post.owner.id}/{self.post.id}/{self.pk}{file_extension}"

    # formImages.is_valid() checks if there is extension to file
    # if file_extension != -1:
    #     return f"posts/{self.post.owner.id}/{self.post.id}/{self.pk}{file_extension}"
    # return f"posts/{self.post.owner.id}/{self.post.id}/{self.pk}.webp"


class Post(models.Model):
    owner = models.ForeignKey(
        "user.MyUserModel", verbose_name=_("Właściciel"), on_delete=models.DO_NOTHING
    )
    description = models.CharField(
        _("Tytuł char"), max_length=1024, blank=True, null=True
    )
    content = models.TextField(_("Zawartość text"), blank=True, null=True)
    added = models.DateTimeField(auto_now_add=False)
    deleted = models.BooleanField(default=False)


def convert_to_webp(image):
    img = Image.open(image)
    output = BytesIO()
    img.save(output, format="WEBP")

    # Przenieś wskaźnik pliku na początek
    output.seek(0)
    # Utwórz obiekt InMemoryUploadedFile z obrazem w formacie WebP
    webp_image = InMemoryUploadedFile(
        output,
        "ImageField",
        "%s.webp" % image.name.split(".")[0],
        "image/webp",
        output.tell(),
        None,
    )
    return webp_image


class PostImage(models.Model):
    # post to which image was added
    post = models.ForeignKey("POST", on_delete=models.DO_NOTHING)
    image = models.ImageField(
        upload_to=get_image_filepath, max_length=255, null=True, blank=True
    )
    deleted = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.image:
            if not guess(self.image).mime.startswith("image/gif"):
                self.image = convert_to_webp(self.image)
        super().save(*args, **kwargs)


class Coment(models.Model):
    post = models.ForeignKey("Post", on_delete=models.DO_NOTHING)
    coment = models.CharField(max_length=1023)
    added = models.DateTimeField(auto_now_add=False)
    owner = models.ForeignKey(
        "user.MyUserModel", verbose_name=_("Właściciel"), on_delete=models.DO_NOTHING
    )
    deleted = models.BooleanField(default=False)

    class Meta:
        ordering = ["-added"]


class Reaction(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    user = models.ForeignKey("user.MyUserModel", on_delete=models.CASCADE)
    # reaction = 1, means that user liked post. reaction = -1 means dislike
    reaction = models.IntegerField(default=0)


class ChatRoom(models.Model):
    first_owner = models.ForeignKey(
        "user.MyUserModel", related_name="first_owner", on_delete=models.CASCADE
    )
    second_owner = models.ForeignKey(
        "user.MyUserModel", related_name="second_owner", on_delete=models.CASCADE
    )
    first_owner_deleted_time = models.DateTimeField(
        auto_now_add=True, null=True, blank=True
    )
    second_owner_deleted_time = models.DateTimeField(
        auto_now_add=True, null=True, blank=True
    )


class UserMessage(models.Model):
    room = models.ForeignKey("ChatRoom", on_delete=models.CASCADE)
    owner = models.ForeignKey(
        "user.MyUserModel", on_delete=models.CASCADE, related_name="from_user"
    )
    message = models.TextField()
    sent = models.DateTimeField(auto_now_add=True)

pages/templates/pages/addPost.html
{% extends "index.html" %}
{% block content %}
    <form class="card p-2"
          method="POST"
          action=""
          enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                {% if field.label|slice:'-4:' == "text" %}
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label|slice:':-5' }}</label>
                    <textarea class="form-control"
                              id="{{ field.id_for_label }}"
                              name="{{ field.name }}"></textarea>
                {% elif field.label|slice:'-4:' == "char" %}
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label|slice:':-5' }}</label>
                    <input type="text"
                           class="form-control"
                           id="{{ field.id_for_label }}"
                           name="{{ field.name }}"/>
                {% endif %}
            </div>
            <br/>
        {% endfor %}
        {% if form_images %}
            <div class="mb-3">
                <label for="formFileMultiple" class="form-label">Dodaj zdjęcie</label>
                <input class="form-control"
                       type="file"
                       name="image"
                       id="formFileMultiple"
                       multiple/>
            </div>
        {% endif %}
        <div class="d-grid gap-2 d-md-block ms-auto">
            <a href="{% url 'home' %}" type="button" class="btn btn-danger">Wróć</a>
            <button type="submit" class="btn btn-primary">Dodaj</button>
        </div>
    </form>
{% endblock %}

pages/templates/pages/chat.html
{% extends "index.html" %}
{% load static %}

{% block content %}
    <div class="card">
        {% include "components/chatNavComponent.html" %}
        <div class="bg-light" id="chat">
            <div class="messages p-1">
                {% for message in chat_messages %}
                    {% if message.owner == request.user %}
                        <div class="card w-75 ms-auto mb-3 me-2">
                            <span class="border-bottom p-1">@{{ message.owner }}, {{ message.sent|timesince }}</span>
                            <span class="p-2">{{ message.message }}</span>
                        </div>
                    {% else %}
                        <div class="card w-75 mb-3 ms-2">
                            <span class="border-bottom p-1">@{{ message.owner }}, {{ message.sent|timesince }}</span>
                            <span class="p-2">{{ message.message }}</span>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>

        <div class="card">
            <form method="POST"
                  action="{% url 'send_message' request.user.id second_user_id %}"
                  class="form-group d-flex w-100 justify-content-between">
                {% csrf_token %}
                <textarea name="message"
                    id="id_message"
                    class="chat-textarea border-0 w-100"
                    placeholder="twoja wiadomość..."></textarea>
                <button class="btn btn-light" id="js-chat-textarea-button" type="submit">
                    <img src="{% static "icons/send.svg" %}" alt="Wyślij">
                </button>
            </form>
        </div>

    </div>

{% endblock %}

pages/templates/pages/home.html
{% extends "index.html" %}
{% block content %}
    <div>
        <a href="{% url 'poast_add' %}"
           class="btn btn-secondary mt-2 w-100 mx-auto">Dodaj posts</a>
        {% for post in posts %}
            <a href="{% url 'post_page' post.id %}">{% include 'components/postShow.html' %}</a>
        {% endfor %}
    </div>
{% endblock %}

pages/templates/pages/messagePage.html
{% extends "index.html" %}
{% load static %}

{% block content %}
    {% for chat in headers %}
        <div class="w-100 card mb-2 p-2">
            <a href="{% url "send_message" chat.first_owner_id chat.second_owner_id %}" class="messages-page-card">
                <div class="d-flex">
                    {% if chat.first_owner_id != request.user.id %}
                        <span>@{{ chat.first_owner__username|truncatechars:13 }}, &nbsp</span>
                    {% else %}
                        <span>@{{ chat.second_owner__username|truncatechars:13 }}, </span>
                    {% endif %}

                    {% include 'components/messageSentTimeComponent.html' %}
                </div>
                <span class="mx-3 text-break">{{ chat.latest_message|truncatechars:128 }}</span>
            </a>
        </div>
    {% endfor %}
{% endblock %}

pages/templates/pages/postView.html
{% extends 'index.html' %}

{% block content %}
    {% include "components/postShow.html" %}
    {% include "components/addComent.html" %}
    {% include "components/comentSection.html" %}
    <div class=" p-2">
    </div>
{% endblock %}